import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter();

  return (
    <div
      className={styles.container}
      onClick={() => {
        router.push("/main");
      }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to HalliGalli</h1>
      </main>
    </div>
  );
};

export default Home;
